## Basic Configuration

baseurl = "http://utkarshshah.com/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Utkarsh Shah"
title = "Utkarsh Shah"

theme = "goa"

## Hugo Built-in Features
PygmentsCodeFences = true
PygmentsStyle = "manni"
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
#enableRobotsTXT = true

## Site Settings
[params]
author = "Utkarsh Shah"
intro = "Developer. Entrepreneur."
description = ""
authorimage = "headshot.jpg"
dateformat = "January 2, 2006"

## Site Meta Settings
[params.meta]
description = "Utkarsh Shah: Software Developer, Entrepreneur"
keywords = "Utkarsh,Shah,Karsh,UPenn,Penn,entrepreneur,developer,computer science"

## Social Accounts
[params.social]
github = "utkarshshah007"
instagram = "shahutk"
linkedin = "utkarshshah1"
twitter = "uss1994"
facebook = "utkarsh.shah1"
email = "utkarsh@utkarshshah.com"

## Extras
[params.extra]
copyright = "© 2017-2018. Utkarsh Shah. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
#[[menu.main]]
#    name = "coderag"
#    identifier = "coderag"
#    weight = 300
#    url = "/coderag/"
